[CP-1392] Refactoring device manager flow
mudita/mudita-center pull request #1047
Opened 2022-11-23 13:25 UTC by igorbezsmertnyi

Jira: [CP-1392]

**Description**

<details>
<summary><b>Screenshots</b></summary>
// put images here
</details>

2022-11-24 13:58 UTC, dkarski commented on packages/app/src/__deprecated__/renderer/wrappers/root-wrapper.tsx
> +      toggleUpdateAvailable(false)
which update? OS or Center? I think that would be nice to keep App as a suffix.

2022-11-24 13:58 UTC, dkarski commented on packages/app/src/crash-dump/observers/crash-dump.observer.test.ts
> +        // } as unknown as DeviceService
to remove?

2022-11-25 07:08 UTC, dkarski requested changes
Please handle the below issues from the list 🙏

Results of the integration tests
- ✅  connect to the Harmony
- ✅  disconnect the Harmony device by unplugging the USB
- ✅  run app with connected Harmony
- ❌  connect to the Pure device by passing a passcode via the Pure device (no redirect to connecting/sync/overview).
- ✅  connect to the Pure device by passing a passcode via Mudita Center
- ✅  connect to the Pure device by passing a passcode via Mudita Center, disconnect and connect again without a passcode
- ✅/ ❌  disconnect by blocking the Pure device ( ❌ -> with a lag on the overview)
- ✅  run app with connected Pure
- ❌  disconnect the Pure device during Sync and reconnect the device throw sync fail & retry sync logic doesn't work properly
- ❌  disconnect the Pure device by unplugging the USB (no redirect to onboarding). (no deterministic, I don't find reproduce path yet)
  - additionally: attach Harmony crash UI/UX logic

2022-11-25 07:25 UTC, dkarski commented on packages/app/src/device-manager/services/device-manager.service.ts
> +  public devicesMap: Map<string, Device> = new Map()
```suggestion
  public devicesMap: Map<string, Device> = new Map<string, Device> ()
```

2022-11-25 07:25 UTC, dkarski commented on packages/app/src/device-manager/services/device-manager.service.ts
> +    return deviceList
🟢 
```suggestion
    return Array.from(this.devicesMap.values()))
```

2022-11-25 07:25 UTC, dkarski commented on packages/app/src/device-manager/services/device-manager.service.ts
> +        this.currentDevice = this.devicesMap.values().next().value
```suggestion
        this.currentDevice = this.devicesMap.values().next().value as Device
```

2022-11-25 12:11 UTC, wojcik92michal reviewed
Just found two small things except the problems found by @dkarski

2022-12-06 08:15 UTC, dkarski approved these changes
> Results of the integration tests
> - ❌ connect to the Pure device by passing a passcode via the Pure device (no redirect to connecting/sync/overview).
> - ✅/ ❌ disconnect by blocking the Pure device ( ❌ -> with a lag on the overview)
✅ run app with connected Pure
> - ❌ disconnect the Pure device during Sync and reconnect the device throw sync fail & retry sync logic doesn't work properly
> - ❌ disconnect the Pure device by unplugging the USB (no redirect to onboarding). (no deterministic, I don't find reproduce path yet)
>   - additionally: attach Harmony crash UI/UX logic

The above issues are fixed 🤞 @wojcik92michal please double check 🙏 

Note:
 - the restore & backup flow will be overwritten in the second PR, so please skip the quality of the code 😅

2022-12-06 08:18 UTC, dkarski approved these changes

2022-12-06 10:47 UTC, merged