[CP-2035] Events related to downloading MuditaOS are stored in Matomo
mudita/mudita-center pull request #1285
Opened 2023-06-22 14:36 UTC by lkowalczyk87

Jira: [CP-2035]

**Description**

<details>
<summary><b>Screenshots</b></summary>
// put images here
</details>

2023-06-25 22:36 UTC, OskarMichalkiewicz approved these changes

2023-06-26 06:19 UTC, dkarski requested changes
It looks like the logic of parse in the latest version has been omitted. I can't approve without making sure it's included.

2023-06-26 06:19 UTC, dkarski commented on packages/app/src/analytic-data-tracker/helpers/track-os-download.ts
> +  const e_a = version
🟡 
It looks like the logic of parse in the latest version has been omitted. This logic is important to collect the root of downloads during the sequence update.

You should send the dedicated prefix with a raw version when the version is the latest. Instead 
`latest` should be `latest - ${releaseVersion}`.

Maybe you included it and I can't read it from the code? 🤔

2023-06-26 06:19 UTC, dkarski commented on packages/app/src/analytic-data-tracker/services/analytic-data-tracker.service.test.ts
> +      expect(response2).toEqual(undefined)
How does this unit test check that the flag is set to false when the body of the logic seems to look similar?

2023-06-26 06:19 UTC, dkarski commented on packages/app/src/analytic-data-tracker/services/analytic-data-tracker.service.ts
> +    if (!this.trackingEnabled || !this.externalUsageDevice) {
🟡 
This check excludes the collection of all events, even those not related to the device. Let's see how to improve this to include compatibility for non-device events (like `CenterVersion`) 😉

2023-06-26 06:19 UTC, dkarski commented on packages/app/src/device/listeners/register-external-usage-device.listner.ts
> +export default registerExternalUsageDevice
🟢 (a good candidate for small PR)
This is a deprecated approach. Please try to rewrite the `listener` to controller & service as a standalone module. I think that this request could merge with the first comment as a good candidate for a small refactor as a standalone PR.

2023-06-26 07:54 UTC, dkarski commented on packages/app/src/analytic-data-tracker/services/analytic-data-tracker.service.test.ts
> +      expect(response2).toEqual(undefined)
I don't see `not`. Sorry @lkowalczyk87

2023-06-26 12:08 UTC, dkarski approved these changes

2023-06-26 12:11 UTC, OskarMichalkiewicz approved these changes

2023-06-26 12:19 UTC, merged