[CP-2667] Add screenshot helper for E2E tests
mudita/mudita-center pull request #1817
Opened 2024-04-07 22:46 UTC by patrycja-paczkowska

JIRA Reference: [CP-2667](https://appnroll.atlassian.net/browse/CP-2667)

### :memo: Description ️

- Add screenshot helper for E2E tests making PNG shot of view or element 
![image](https://github.com/mudita/mudita-center/assets/88655668/0f2ce2dc-3212-4ebf-8175-82ba76ec8c35)

### :muscle: Checklist before requesting a review - nice to have

- getState function in async thunk actions is correctly typed
- redux selectors are used in components / prop drilling is reduce

### :exclamation: Checklist before merging a pull request

- change went through the QA process
- translations are updated in dedicated application
- [CHANGELOG.md](./CHANGELOG.md) is updated

2024-04-08 07:30 UTC, tomaszmaleckimudita requested changes
Check branch `CP-2667-tomasz-test` - makeElementScreenshot doesn't respond for me (folder is created but it is empty)

2024-04-08 07:30 UTC, tomaszmaleckimudita commented on apps/mudita-center-e2e/src/helpers/screenshot.helper.ts
> +const generateFilename = (baseName: string, elementName?: string) => {
Move method inside a class and use `this.generateFilename` and variables like this: `this.screenshotDir`, `this.viewsDir`, `this.elementsDir` 

```suggestion
class ScreenshotHelper {
  screenshotsDir = "./screenshots"
  viewsDir = path.join(this.screenshotsDir, "views")
  elementsDir = path.join(this.screenshotsDir, "elements")

  generateFilename = (baseName: string, elementName?: string) => {
    const currentDate = new Date()
    const millisecondsInMinute = 60 * 1000
    const timezoneOffsetMs =
      currentDate.getTimezoneOffset() * millisecondsInMinute
    const dateAsISOString = new Date(
      currentDate.getTime() - timezoneOffsetMs
    ).toISOString()
```

2024-04-08 09:06 UTC, patrycja-paczkowska commented on apps/mudita-center-e2e/src/helpers/screenshot.helper.ts
> +    currentDate.getTimezoneOffset() * millisecondsInMinute
I tried to avoid magic numbers, this way the code is more self-explanatory

2024-04-10 13:42 UTC, lkowalczyk87 submitted a review, later dismissed

2024-04-11 07:19 UTC, tomaszmaleckimudita approved these changes

2024-04-11 08:01 UTC, merged