[CP-2749] [E2E][HomePage] MC Update available - Force Update
mudita/mudita-center pull request #1964
Opened 2024-07-09 11:15 UTC by patrycja-paczkowska

JIRA Reference: [CP-2749](https://appnroll.atlassian.net/browse/CP-2749)

### :memo: Description ️

- TBD

### :muscle: Checklist before requesting a review - nice to have

- getState function in async thunk actions is correctly typed
- redux selectors are used in components / prop drilling is reduce

### :exclamation: Checklist before merging a pull request

- change went through the QA process
- translations are updated in dedicated application
- [CHANGELOG.md](./CHANGELOG.md) is updated

2024-07-10 09:34 UTC, tomaszmaleckimudita requested changes

2024-07-10 09:34 UTC, tomaszmaleckimudita commented on apps/mudita-center-e2e/src/page-objects/modal-app-update.page.ts
> +class ModalAppUpdate extends Page {
All modals are extending Page, We should probably change this in a future

2024-07-10 09:34 UTC, tomaszmaleckimudita commented on apps/mudita-center-e2e/src/page-objects/modal-app-update.page.ts
> +      "p*=Please accept the Privacy Policy to start updating Mudita Center."
Can you make it single line? 
```
      return $("p*=Please accept the Privacy Policy to start updating Mudita Center.")
```

2024-07-10 09:34 UTC, tomaszmaleckimudita commented on apps/mudita-center-e2e/src/specs/overview/e2e-mock-mc-force-update-available.e2e.ts
> +    await console.log("AVAILABLE VERSION:" + availableAppVersion)
Please remove console logs

2024-07-10 09:34 UTC, tomaszmaleckimudita commented on apps/mudita-center-e2e/src/specs/overview/e2e-mock-mc-force-update-available.e2e.ts
> +    await console.log("CURRENT VERSION:" + currentAppVersion)
Please remove console logs

2024-07-10 09:34 UTC, tomaszmaleckimudita commented on apps/mudita-center-e2e/wdio.conf.ts
> +      toRelativePath(TestFilesPaths.mcHomePageForceUpdateTest),
This is not a standalone test anymore. We decided everything that uses mocks should be in  `mock: []`

* Kompakt mocks
* Offline mocking
* Force Update / Soft Update MC mocking

2024-07-10 09:34 UTC, tomaszmaleckimudita commented
Can't test on Windows, no `.exe` build available. Requested unblocking `Build & deploy to feature branch / build (Windows)`

2024-07-10 13:06 UTC, tomaszmaleckimudita requested changes

2024-07-10 13:06 UTC, tomaszmaleckimudita commented on apps/mudita-center-e2e/src/specs/overview/e2e-mock-mc-force-update-available.e2e.ts
> +    await console.log("AVAILABLE VERSION:" + availableAppVersion)
expect(availableVersion) to be same as E2EMockClient.setMockUpdateState.version ?

2024-07-23 16:03 UTC, patrycja-paczkowska commented on apps/mudita-center-e2e/src/page-objects/modal-app-update.page.ts
> +      "p*=Please accept the Privacy Policy to start updating Mudita Center."
Prettier

2024-07-25 07:00 UTC, tomaszmaleckimudita approved these changes
Works good on all systems

2024-07-25 07:00 UTC, merged