CP-2919-pause-fix added loop and pause
mudita/mudita-center pull request #2065
Opened 2024-09-17 11:26 UTC by robertmudi

JIRA Reference: [CP-3068]

### :memo: Description ️
Test fixes the device-drawer stress test. Now only device drawer is displayed instead of select device modal
-

### :muscle: Checklist before requesting a review - nice to have

- getState function in async thunk actions is correctly typed
- redux selectors are used in components / prop drilling is reduce

### :exclamation: Checklist before merging a pull request

- change went through the QA process
- translations are updated in dedicated application
- [CHANGELOG.md](./CHANGELOG.md) is updated

2024-09-17 13:13 UTC, dkarski approved these changes

2024-09-17 13:30 UTC, tomaszmaleckimudita requested changes

2024-09-17 13:30 UTC, tomaszmaleckimudita commented on apps/mudita-center-e2e/src/specs/stress-tests/device-drawer-stress-test.ts
> +      if (i === 0) {
```suggestion     

      // Add a 4-second wait after adding the first device
      if (i === 0) {
        await browser.pause(10000)
      } 
     else {
      await browser.pause(6000)
      }
```

2024-09-17 13:32 UTC, tomaszmaleckimudita requested changes

2024-09-17 13:32 UTC, tomaszmaleckimudita commented on apps/mudita-center-e2e/src/specs/stress-tests/device-drawer-stress-test.ts
> +      }
```suggestion
      // Add a 4-second wait after adding the first device
      if (i === 0) {
        await browser.pause(10000)
      } else {
      await browser.pause(6000)
      }
```

2024-09-17 17:58 UTC, robertmudi commented on apps/mudita-center-e2e/src/specs/stress-tests/device-drawer-stress-test.ts
> +      }
simplified the test

2024-09-18 06:59 UTC, dkarski approved these changes

2024-09-18 07:04 UTC, tomaszmaleckimudita approved these changes
Works ok

2024-09-18 07:04 UTC, merged