[CP-1516][Messages] Importing contacts via MS Outlook is limited to 10 entries and lacks phone numbers
mudita/mudita-center pull request #903
Opened 2022-08-09 13:59 UTC by dkarski

Jira: [CP-1516]

**Description**

2022-08-09 14:00 UTC, igorbezsmertnyi commented on packages/app/src/contacts/helpers/map-vcfs-to-contacts/map-vcfs-to-contacts.ts
> +  } catch (e) {
???

2022-08-09 14:02 UTC, dkarski commented on packages/app/src/contacts/helpers/map-vcfs-to-contacts/map-vcfs-to-contacts.ts
> +  } catch (e) {
I'm joking. Thanks 🙇

2022-08-09 14:08 UTC, igorbezsmertnyi approved these changes

2022-08-09 14:14 UTC, igorbezsmertnyi requested changes
Please fix tests

2022-08-19 05:20 UTC, dkarski commented
This logic isn't related to the outlook import process. The right fix is here 👉 https://github.com/mudita/mudita-center/pull/923

2022-08-19 05:20 UTC, closed without merging