[CP-1090] Implementing infinity loading for large contacts lists
mudita/mudita-center pull request #966
Opened 2022-09-08 07:01 UTC by igorbezsmertnyi

Jira: [CP-1090]

**Description**
Implementing infinity loading for large contacts lists

<details>
<summary><b>Screenshots</b></summary>
// put images here
</details>

2022-09-08 08:45 UTC, wojcik92michal requested changes
Rejecting due to the fact that contacts search is now broken.

2022-09-08 08:48 UTC, wercix submitted a review, later dismissed

2022-09-09 13:34 UTC, wercix reviewed
Looks good, search is working. But now after checking a checkbox the list is loaded one more time. Can we improve this experience?

2022-09-12 08:39 UTC, igorbezsmertnyi commented
@wercix https://github.com/mudita/mudita-center/pull/966/commits/da92d060b575c56715c7b41cc0aec8e29fd86164

2022-09-13 07:06 UTC, igorbezsmertnyi commented
@wojcik92michal

2022-09-13 08:14 UTC, wojcik92michal commented on packages/app/src/contacts/components/contact-group/contact-group.styled.ts
> +/**
(adding it here as it is easier to have a thread)

1. Row context menu in some cases is clipped
2. There are two scrolls in the list - one for the whole list and one for the "letter group"

https://user-images.githubusercontent.com/41268731/189847637-1ccc93ba-8e62-4ee8-87e3-3d279f3e4e4f.mov

2022-09-21 09:40 UTC, wercix commented
@igorbezsmertnyi could you please close this draft?

2022-09-27 07:06 UTC, wojcik92michal commented
Handled by another PR, https://github.com/mudita/mudita-center/pull/977

2022-09-27 07:06 UTC, closed without merging